# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-03-26 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.UUIDField()),
                ('enterprise_name', models.CharField(max_length=255)),
                ('lms_user_id', models.PositiveIntegerField()),
                ('course_id', models.CharField(help_text='The course the learner is enrolled in.', max_length=255)),
                ('enrollment_created_timestamp', models.DateTimeField()),
                ('user_current_enrollment_mode', models.CharField(max_length=32)),
                ('consent_granted', models.NullBooleanField(default=None)),
                ('letter_grade', models.CharField(max_length=32, null=True)),
                ('has_passed', models.BooleanField(default=False)),
                ('passed_timestamp', models.DateTimeField(null=True)),
                ('enterprise_sso_uid', models.CharField(max_length=255, null=True)),
                ('enterprise_site_id', models.PositiveIntegerField(null=True)),
                ('course_title', models.CharField(max_length=255, null=True)),
                ('course_start', models.DateTimeField(null=True)),
                ('course_end', models.DateTimeField(null=True)),
                ('course_pacing_type', models.CharField(max_length=32, null=True)),
                ('course_duration_weeks', models.CharField(max_length=32, null=True)),
                ('course_min_effort', models.PositiveIntegerField(null=True)),
                ('course_max_effort', models.PositiveIntegerField(null=True)),
                ('user_account_creation_timestamp', models.DateTimeField(null=True)),
                ('user_email', models.CharField(max_length=255, null=True)),
                ('user_username', models.CharField(max_length=255, null=True)),
                ('course_key', models.CharField(max_length=255, null=True)),
                ('user_country_code', models.CharField(max_length=2, null=True)),
                ('last_activity_date', models.DateField(null=True)),
                ('coupon_name', models.CharField(max_length=128, null=True)),
                ('coupon_code', models.CharField(max_length=128, null=True)),
                ('offer', models.CharField(max_length=128, null=True)),
                ('current_grade', models.FloatField(null=True)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('unenrollment_timestamp', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'enterprise_enrollment',
                'verbose_name': 'Enterprise Enrollment',
                'verbose_name_plural': 'Enterprise Enrollments',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.UUIDField()),
                ('lms_user_id', models.PositiveIntegerField()),
                ('enterprise_user_id', models.PositiveIntegerField(unique=True)),
                ('enterprise_sso_uid', models.CharField(max_length=255, null=True)),
                ('user_account_creation_timestamp', models.DateTimeField(null=True)),
                ('user_email', models.CharField(max_length=255, null=True)),
                ('user_username', models.CharField(max_length=255, null=True)),
                ('user_country_code', models.CharField(max_length=2, null=True)),
                ('last_activity_date', models.DateField(null=True)),
                ('created', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-user_email'],
                'db_table': 'enterprise_user',
                'verbose_name': 'Enterprise User',
                'verbose_name_plural': 'Enterprise Users',
            },
        ),
        migrations.AddField(
            model_name='enterpriseenrollment',
            name='enterprise_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enterprise_data.EnterpriseUser', to_field='enterprise_user_id'),
        ),
    ]